<?php
/**
 * ============================================================================
 * SECURE FILE UPLOAD SYSTEM — DEPLOYMENT SCRIPT
 * ============================================================================
 * 
 * Drop this file into the ROOT of your project (same level as login.php)
 * and open it in the browser:
 * 
 *   http://localhost/your-project/deploy_file_uploader.php
 * 
 * What it does:
 *   1. Creates includes/file_uploader.php (centralized secure upload handler)
 *   2. Adds .htaccess security to upload directories
 *   3. Ensures config.php includes file_uploader.php
 *   4. Adds file_upload_audit table schema to db_schema.php
 *   5. [BUTTON] Creates the file_upload_audit table in the database
 *   6. Shows a security checklist
 * 
 * Safety:
 *   - Idempotent — safe to run multiple times
 *   - Creates .bak backups before modifying files
 *   - Table creation only on button click (with IF NOT EXISTS)
 * 
 * After deployment, DELETE this file.
 * ============================================================================
 */

$IS_CLI = (php_sapi_name() === 'cli');
$BASE   = __DIR__;

// ---- Output helpers -------------------------------------------------------
function out($msg, $type = 'info') {
    global $IS_CLI;
    $icons = ['ok' => '&#10004;', 'skip' => '&#8680;', 'err' => '&#10008;', 'info' => '&#8505;', 'warn' => '&#9888;'];
    $icon  = $icons[$type] ?? '';
    if ($IS_CLI) {
        $prefix = ['ok'=>'[OK]','skip'=>'[SKIP]','err'=>'[ERR]','info'=>'[INFO]','warn'=>'[WARN]'][$type] ?? '[--]';
        echo "$prefix $msg\n";
    } else {
        $colors = ['ok'=>'#28a745','skip'=>'#6c757d','err'=>'#dc3545','info'=>'#17a2b8','warn'=>'#ffc107'];
        $color  = $colors[$type] ?? '#333';
        echo "<div style='padding:6px 12px;margin:3px 0;font-family:monospace;font-size:14px;color:$color;'>$icon $msg</div>\n";
    }
}
function heading($title) {
    global $IS_CLI;
    if ($IS_CLI) echo "\n=== $title ===\n";
    else echo "<h3 style='margin:20px 0 8px;font-family:monospace;color:#fff;background:#1e1e2e;padding:10px 15px;border-radius:6px;'>$title</h3>\n";
}
function backup($path) {
    $bak = $path . '.bak.' . date('Ymd_His');
    if (copy($path, $bak)) { out("Backup: " . basename($bak), 'info'); return true; }
    out("Backup failed: " . basename($path), 'err'); return false;
}

// ---- Handle table creation button press -----------------------------------
$table_action = $_POST['create_table'] ?? '';

// ---- Start HTML output ----------------------------------------------------
if (!$IS_CLI) {
    echo '<!DOCTYPE html><html><head><meta charset="utf-8"><title>File Upload System Deployment</title>'
       . '<style>'
       . 'body{background:#0d1117;color:#c9d1d9;font-family:monospace;padding:20px 40px;max-width:1000px;margin:0 auto;}'
       . '.btn{display:inline-block;padding:12px 28px;border:none;border-radius:6px;font-size:16px;font-family:monospace;cursor:pointer;margin:10px 5px;}'
       . '.btn-green{background:#238636;color:#fff;}.btn-green:hover{background:#2ea043;}'
       . '.btn-blue{background:#1f6feb;color:#fff;}.btn-blue:hover{background:#388bfd;}'
       . '.box{background:#161b22;border:1px solid #30363d;border-radius:8px;padding:15px;margin:15px 0;}'
       . '</style></head><body>';
    echo '<h1 style="color:#58a6ff;">&#128274; Secure File Upload System — Deployment</h1><hr style="border-color:#30363d;">';
}

// ============================================================================
// STEP 1: Create includes/file_uploader.php
// ============================================================================
heading('Step 1 — Create includes/file_uploader.php');

$uploader_path = $BASE . '/includes/file_uploader.php';

if (!is_dir($BASE . '/includes')) {
    out("includes/ directory not found. Is this the correct project root?", 'err');
    if (!$IS_CLI) echo '</body></html>';
    exit(1);
}

if (file_exists($uploader_path) && strpos(file_get_contents($uploader_path), 'FILE_UPLOADER_LOADED') !== false) {
    out("file_uploader.php already exists and is up to date", 'skip');
} else {
    if (file_exists($uploader_path)) backup($uploader_path);
    file_put_contents($uploader_path, get_file_uploader_content());
    out("file_uploader.php created successfully", 'ok');
}

// ============================================================================
// STEP 2: Add .htaccess security to upload directories
// ============================================================================
heading('Step 2 — Secure upload directories with .htaccess');

$upload_dirs = [
    $BASE . '/uploads',
    $BASE . '/assets/uploads',
];

$htaccess_content = <<<'HTACCESS'
# Prevent PHP/script execution in upload directory
# Generated by deploy_file_uploader.php

<IfModule mod_php.c>
    php_flag engine off
</IfModule>
<IfModule mod_php7.c>
    php_flag engine off
</IfModule>
<IfModule mod_php8.c>
    php_flag engine off
</IfModule>

<FilesMatch "\.(php|phtml|php3|php4|php5|php7|php8|phar|cgi|pl|py|rb|sh|bash|bat|cmd|exe|com)$">
    Require all denied
</FilesMatch>

<IfModule mod_headers.c>
    Header set X-Content-Type-Options "nosniff"
</IfModule>
HTACCESS;

foreach ($upload_dirs as $dir) {
    if (!is_dir($dir)) {
        @mkdir($dir, 0755, true);
        out("Created directory: " . str_replace($BASE . '/', '', $dir), 'ok');
    }
    $htaccess_path = $dir . '/.htaccess';
    if (file_exists($htaccess_path)) {
        out(".htaccess already exists in " . str_replace($BASE . '/', '', $dir), 'skip');
    } else {
        file_put_contents($htaccess_path, $htaccess_content);
        out(".htaccess created in " . str_replace($BASE . '/', '', $dir), 'ok');
    }
}

// ============================================================================
// STEP 3: Ensure config.php includes file_uploader.php
// ============================================================================
heading('Step 3 — Ensure config.php includes file_uploader.php');

$config_path = $BASE . '/includes/config.php';
if (!file_exists($config_path)) {
    out("config.php not found!", 'err');
} else {
    $config_content = file_get_contents($config_path);
    if (strpos($config_content, 'file_uploader.php') !== false) {
        out("config.php already includes file_uploader.php", 'skip');
    } else {
        backup($config_path);
        // Insert after error_handler.php include
        if (strpos($config_content, 'error_handler.php') !== false) {
            $config_content = preg_replace(
                '/(require_once\s+__DIR__\s*\.\s*\'\/error_handler\.php\'\s*;)/',
                "$1\n\n// Load centralized secure file upload handler\nrequire_once __DIR__ . '/file_uploader.php';",
                $config_content,
                1
            );
        } else {
            // Fallback: insert after <?php
            $config_content = preg_replace(
                '/(<\?php\s*\n)/',
                "$1\n// Load centralized secure file upload handler\nrequire_once __DIR__ . '/file_uploader.php';\n",
                $config_content,
                1
            );
        }
        file_put_contents($config_path, $config_content);
        out("Added file_uploader.php include to config.php", 'ok');
    }
}

// ============================================================================
// STEP 4: Add file_upload_audit schema to db_schema.php
// ============================================================================
heading('Step 4 — Add file_upload_audit table schema to db_schema.php');

$schema_path = $BASE . '/includes/db_schema.php';
if (!file_exists($schema_path)) {
    out("db_schema.php not found — skipping schema update", 'warn');
} else {
    $schema_content = file_get_contents($schema_path);
    if (strpos($schema_content, 'file_upload_audit') !== false) {
        out("file_upload_audit schema already exists in db_schema.php", 'skip');
    } else {
        backup($schema_path);

        // Add table definition before the closing ];
        $audit_schema = <<<'SCHEMA'

    // File Upload Audit table (tracks all upload attempts for security monitoring)
    'file_upload_audit' => [
        'sql' => "CREATE TABLE IF NOT EXISTS file_upload_audit (
            id INT AUTO_INCREMENT PRIMARY KEY,
            user_id INT NOT NULL COMMENT 'ID of the user who attempted the upload',
            ip_address VARCHAR(45) NOT NULL COMMENT 'Client IP address',
            original_filename VARCHAR(255) NOT NULL COMMENT 'Original filename from client',
            saved_filename VARCHAR(255) NULL COMMENT 'Filename saved on server (NULL if rejected)',
            file_size INT UNSIGNED NOT NULL DEFAULT 0 COMMENT 'File size in bytes',
            mime_type VARCHAR(100) NULL COMMENT 'Detected MIME type (server-side)',
            upload_context VARCHAR(50) NOT NULL COMMENT 'Context: profile_photo, task_attachment, report, etc.',
            status ENUM('accepted','rejected','error') NOT NULL DEFAULT 'accepted',
            rejection_reason VARCHAR(255) NULL COMMENT 'Reason for rejection (NULL if accepted)',
            created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
            INDEX idx_audit_user (user_id),
            INDEX idx_audit_status (status),
            INDEX idx_audit_context (upload_context),
            INDEX idx_audit_created (created_at),
            INDEX idx_audit_ip (ip_address)
        ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci"
    ]
SCHEMA;

        // Find the last table entry and append before ];
        $schema_content = preg_replace(
            '/(\]\s*\n)(\s*\];\s*\n\s*\/\/ Table creation order)/',
            "$1,$audit_schema\n$2",
            $schema_content,
            1,
            $count
        );

        if ($count > 0) {
            // Also add to TABLE_CREATION_ORDER
            $schema_content = preg_replace(
                "/(\'rate_limits\'\s*\n)(\s*\];)/",
                "$1    'file_upload_audit',\n$2",
                $schema_content,
                1
            );
            file_put_contents($schema_path, $schema_content);
            out("Added file_upload_audit schema to db_schema.php", 'ok');
        } else {
            out("Could not auto-insert schema — add manually", 'warn');
        }
    }
}

// ============================================================================
// STEP 5: Create file_upload_audit table (BUTTON)
// ============================================================================
heading('Step 5 — Create file_upload_audit table in database');

// Try to load database connection
$conn = null;
if (file_exists($config_path)) {
    // Suppress output from config.php
    ob_start();
    try {
        // Check if $conn is already available
        if (!isset($conn) || !$conn) {
            require_once $config_path;
        }
    } catch (Exception $e) {
        // ignore
    }
    ob_end_clean();
}

$table_sql = "CREATE TABLE IF NOT EXISTS file_upload_audit (
    id INT AUTO_INCREMENT PRIMARY KEY,
    user_id INT NOT NULL COMMENT 'ID of the user who attempted the upload',
    ip_address VARCHAR(45) NOT NULL COMMENT 'Client IP address',
    original_filename VARCHAR(255) NOT NULL COMMENT 'Original filename from client',
    saved_filename VARCHAR(255) NULL COMMENT 'Filename saved on server (NULL if rejected)',
    file_size INT UNSIGNED NOT NULL DEFAULT 0 COMMENT 'File size in bytes',
    mime_type VARCHAR(100) NULL COMMENT 'Detected MIME type (server-side)',
    upload_context VARCHAR(50) NOT NULL COMMENT 'Context: profile_photo, task_attachment, report, etc.',
    status ENUM('accepted','rejected','error') NOT NULL DEFAULT 'accepted',
    rejection_reason VARCHAR(255) NULL COMMENT 'Reason for rejection (NULL if accepted)',
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    INDEX idx_audit_user (user_id),
    INDEX idx_audit_status (status),
    INDEX idx_audit_context (upload_context),
    INDEX idx_audit_created (created_at),
    INDEX idx_audit_ip (ip_address)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci";

if ($table_action === 'yes' && $conn) {
    // Check if table already exists
    $check = mysqli_query($conn, "SHOW TABLES LIKE 'file_upload_audit'");
    if ($check && mysqli_num_rows($check) > 0) {
        out("Table file_upload_audit already exists — no action needed", 'skip');
    } else {
        if (mysqli_query($conn, $table_sql)) {
            out("Table file_upload_audit created successfully!", 'ok');
        } else {
            out("Failed to create table: " . mysqli_error($conn), 'err');
        }
    }
} elseif ($table_action === 'yes' && !$conn) {
    out("No database connection available. Check config.php.", 'err');
} else {
    // Show table status and button
    if ($conn) {
        $check = mysqli_query($conn, "SHOW TABLES LIKE 'file_upload_audit'");
        if ($check && mysqli_num_rows($check) > 0) {
            out("Table file_upload_audit already exists in the database", 'ok');
            
            // Show row count
            $count_result = mysqli_query($conn, "SELECT COUNT(*) as cnt FROM file_upload_audit");
            if ($count_result) {
                $row = mysqli_fetch_assoc($count_result);
                out("Current audit log entries: " . $row['cnt'], 'info');
            }
        } else {
            out("Table file_upload_audit does NOT exist yet.", 'warn');
            if (!$IS_CLI) {
                echo '<div class="box">';
                echo '<p style="color:#c9d1d9;font-size:15px;">Click the button below to create the <code>file_upload_audit</code> table in your database.</p>';
                echo '<p style="color:#8b949e;font-size:13px;">Uses <code>CREATE TABLE IF NOT EXISTS</code> — safe to click even if table already exists.</p>';
                echo '<form method="POST">';
                echo '<button type="submit" name="create_table" value="yes" class="btn btn-green">&#128274; Create file_upload_audit Table</button>';
                echo '</form>';
                echo '</div>';
            }
        }
    } else {
        out("No database connection — cannot check table status", 'warn');
        if (!$IS_CLI) {
            echo '<div class="box">';
            echo '<p style="color:#ffc107;">Could not establish database connection from config.php.</p>';
            echo '<p>You can still create the table manually with this SQL:</p>';
            echo '<pre style="background:#0d1117;padding:10px;border-radius:4px;overflow-x:auto;font-size:12px;color:#c9d1d9;">' . htmlspecialchars($table_sql) . '</pre>';
            echo '</div>';
        }
    }
}

// ============================================================================
// STEP 6: Verification & Security Checklist
// ============================================================================
heading('Step 6 — Verification & Security Checklist');

$checks = [
    ['file_uploader.php exists', file_exists($uploader_path)],
    ['config.php includes file_uploader.php', file_exists($config_path) && strpos(file_get_contents($config_path), 'file_uploader.php') !== false],
    ['uploads/.htaccess exists', file_exists($BASE . '/uploads/.htaccess')],
    ['assets/uploads/.htaccess exists', file_exists($BASE . '/assets/uploads/.htaccess')],
    ['db_schema.php has file_upload_audit', file_exists($schema_path) && strpos(file_get_contents($schema_path), 'file_upload_audit') !== false],
];

foreach ($checks as [$label, $ok]) {
    out($label, $ok ? 'ok' : 'err');
}

// ============================================================================
// Summary
// ============================================================================
heading('Deployment Summary');

if (!$IS_CLI) echo '<div class="box">';
out("Secure File Upload System deployed successfully.", 'ok');
out("", 'info');
out("Functions available in all files that include config.php:", 'info');
out("  secureUpload(\$conn, \$file, 'context')           — validate + save \$_FILES upload", 'info');
out("  secureBase64Upload(\$conn, \$data, \$name, 'ctx')  — validate + save base64 upload", 'info');
out("  getUploadContextConfig('context')                 — get context configuration", 'info');
out("", 'info');
out("Upload contexts: profile_photo, task_attachment, report, update_attachment, voice_recording, holiday_csv", 'info');
out("", 'info');
out("IMPORTANT: Delete this deployment script after running!", 'warn');
out("IMPORTANT: You still need to refactor handler files to call secureUpload() — see project docs.", 'warn');
if (!$IS_CLI) echo '</div>';

if (!$IS_CLI) echo '</body></html>';

// ============================================================================
// Full content of includes/file_uploader.php
// ============================================================================
function get_file_uploader_content() {
    return <<<'FILEUPLOADER'
<?php
/**
 * Centralized Secure File Upload Handler
 * 
 * SECURITY FEATURES:
 * - Server-side MIME validation using finfo (not client-spoofable $_FILES['type'])
 * - Extension whitelist per upload context
 * - Blocked dangerous extensions (PHP, EXE, etc.)
 * - Double extension detection (e.g., evil.php.jpg)
 * - PHP code injection scanning in uploaded files
 * - Null byte / directory traversal protection
 * - File size limits per context
 * - Upload audit logging to database
 * - Safe filename generation (no user input in stored names)
 * 
 * USAGE:
 *   $result = secureUpload($conn, $_FILES['file'], 'task_attachment');
 *   if ($result['success']) {
 *       $savedPath = $result['relative_path'];
 *   } else {
 *       $error = $result['error'];
 *   }
 */

if (defined('FILE_UPLOADER_LOADED')) { return; }
define('FILE_UPLOADER_LOADED', true);

define('UPLOAD_CONTEXTS', [
    'profile_photo'     => ['allowed_extensions' => ['jpg','jpeg','png','gif'],                                                                                   'max_size' => 5*1024*1024,  'upload_dir' => 'assets/uploads/profile_photos/'],
    'task_attachment'    => ['allowed_extensions' => ['pdf','doc','docx','xls','xlsx','txt','jpg','jpeg','png','gif','mp4','avi','mov','mp3','wav'],                'max_size' => 50*1024*1024, 'upload_dir' => 'uploads/task_ticket/'],
    'report'            => ['allowed_extensions' => ['pdf','ppt','pptx','doc','docx','txt'],                                                                      'max_size' => 50*1024*1024, 'upload_dir' => 'uploads/reports/'],
    'update_attachment'  => ['allowed_extensions' => ['pdf','doc','docx','xls','xlsx','txt','jpg','jpeg','png','gif','mp4','avi','mov','mp3','wav','webm'],         'max_size' => 50*1024*1024, 'upload_dir' => 'uploads/updates/'],
    'voice_recording'   => ['allowed_extensions' => ['webm','ogg','mp3','wav'],                                                                                   'max_size' => 20*1024*1024, 'upload_dir' => 'uploads/updates/voice/'],
    'holiday_csv'       => ['allowed_extensions' => ['csv','xlsx'],                                                                                                'max_size' => 10*1024*1024, 'upload_dir' => 'uploads/holidays/'],
]);

define('UPLOAD_MIME_MAP', [
    'jpg'=>['image/jpeg'],'jpeg'=>['image/jpeg'],'png'=>['image/png'],'gif'=>['image/gif'],
    'pdf'=>['application/pdf'],
    'doc'=>['application/msword','application/octet-stream'],'docx'=>['application/vnd.openxmlformats-officedocument.wordprocessingml.document','application/zip','application/octet-stream'],
    'xls'=>['application/vnd.ms-excel','application/octet-stream'],'xlsx'=>['application/vnd.openxmlformats-officedocument.spreadsheetml.sheet','application/zip','application/octet-stream'],
    'ppt'=>['application/vnd.ms-powerpoint','application/octet-stream'],'pptx'=>['application/vnd.openxmlformats-officedocument.presentationml.presentation','application/zip','application/octet-stream'],
    'txt'=>['text/plain'],'csv'=>['text/csv','text/plain','application/csv','application/octet-stream'],
    'mp4'=>['video/mp4','application/octet-stream'],'avi'=>['video/x-msvideo','application/octet-stream'],'mov'=>['video/quicktime','application/octet-stream'],
    'mp3'=>['audio/mpeg','audio/mp3','application/octet-stream'],'wav'=>['audio/wav','audio/x-wav','application/octet-stream'],
    'webm'=>['video/webm','audio/webm','application/octet-stream'],'ogg'=>['audio/ogg','application/ogg','application/octet-stream'],
]);

define('BLOCKED_EXTENSIONS', [
    'php','phtml','php3','php4','php5','php7','php8','phar','cgi','pl','py','rb','sh','bash',
    'bat','cmd','com','exe','msi','scr','vbs','vbe','js','wsh','wsf',
    'htaccess','htpasswd','ini','env','asp','aspx','jsp','jspx',
]);

function secureUpload($conn, $file, $context, $options = []) {
    $userId = $_SESSION['id'] ?? $_SESSION['user_id'] ?? 0;
    $ip = function_exists('getClientIpAddress') ? getClientIpAddress() : ($_SERVER['REMOTE_ADDR'] ?? '0.0.0.0');
    $config = _getContextConfig($context, $options);
    if (!$config) return _uploadFailure($conn,$userId,$ip,$file['name']??'unknown',0,null,$context,"Unknown upload context: {$context}");
    $originalName = _sanitizeFilename($file['name'] ?? 'unknown');
    $fileSize = $file['size'] ?? 0;
    if (($file['error'] ?? UPLOAD_ERR_OK) !== UPLOAD_ERR_OK) return _uploadFailure($conn,$userId,$ip,$originalName,$fileSize,null,$context,_uploadErrorMessage($file['error']));
    $ext = strtolower(pathinfo($originalName, PATHINFO_EXTENSION));
    if (in_array($ext, BLOCKED_EXTENSIONS)) return _uploadFailure($conn,$userId,$ip,$originalName,$fileSize,null,$context,"Blocked file type: .{$ext}");
    if (!in_array($ext, $config['allowed_extensions'])) return _uploadFailure($conn,$userId,$ip,$originalName,$fileSize,null,$context,"File type .{$ext} not allowed. Allowed: ".implode(', ',$config['allowed_extensions']));
    if (_hasDoubleExtension($originalName)) return _uploadFailure($conn,$userId,$ip,$originalName,$fileSize,null,$context,"Double extension detected");
    if ($fileSize > $config['max_size']) return _uploadFailure($conn,$userId,$ip,$originalName,$fileSize,null,$context,"File exceeds ".round($config['max_size']/(1024*1024),1)."MB limit");
    $detectedMime = null;
    if (function_exists('finfo_open') && !empty($file['tmp_name']) && file_exists($file['tmp_name'])) {
        $finfo = finfo_open(FILEINFO_MIME_TYPE); $detectedMime = finfo_file($finfo, $file['tmp_name']); finfo_close($finfo);
        if (!_isAllowedMime($ext, $detectedMime)) return _uploadFailure($conn,$userId,$ip,$originalName,$fileSize,$detectedMime,$context,"MIME mismatch: content is '{$detectedMime}' but extension is .{$ext}");
    }
    if (!empty($file['tmp_name']) && file_exists($file['tmp_name']) && _containsPhpCode($file['tmp_name'])) return _uploadFailure($conn,$userId,$ip,$originalName,$fileSize,$detectedMime,$context,"File contains embedded script code");
    $newFilename = _generateSafeFilename($ext);
    $absDir = _getAbsoluteUploadDir($config['upload_dir']);
    if (!_ensureDirectoryExists($absDir)) return _uploadFailure($conn,$userId,$ip,$originalName,$fileSize,$detectedMime,$context,"Failed to create upload directory");
    if (!move_uploaded_file($file['tmp_name'], $absDir.$newFilename)) return _uploadFailure($conn,$userId,$ip,$originalName,$fileSize,$detectedMime,$context,"Failed to save file");
    @chmod($absDir.$newFilename, 0644);
    _logAudit($conn,$userId,$ip,$originalName,$newFilename,$fileSize,$detectedMime,$context,'accepted');
    return ['success'=>true,'filename'=>$newFilename,'original_name'=>$originalName,'relative_path'=>$config['upload_dir'].$newFilename,'file_size'=>$fileSize,'mime_type'=>$detectedMime??($file['type']??'application/octet-stream'),'error'=>null];
}

function secureBase64Upload($conn, $base64Data, $originalName, $context, $options = []) {
    $userId = $_SESSION['id'] ?? $_SESSION['user_id'] ?? 0;
    $ip = function_exists('getClientIpAddress') ? getClientIpAddress() : ($_SERVER['REMOTE_ADDR'] ?? '0.0.0.0');
    $originalName = _sanitizeFilename($originalName);
    $config = _getContextConfig($context, $options);
    if (!$config) return _uploadFailure($conn,$userId,$ip,$originalName,0,null,$context,"Unknown upload context: {$context}");
    $ext = strtolower(pathinfo($originalName, PATHINFO_EXTENSION));
    if (in_array($ext, BLOCKED_EXTENSIONS)) return _uploadFailure($conn,$userId,$ip,$originalName,0,null,$context,"Blocked file type: .{$ext}");
    if (!in_array($ext, $config['allowed_extensions'])) return _uploadFailure($conn,$userId,$ip,$originalName,0,null,$context,"File type .{$ext} not allowed");
    if (_hasDoubleExtension($originalName)) return _uploadFailure($conn,$userId,$ip,$originalName,0,null,$context,"Double extension detected");
    $fileData = base64_decode($base64Data, true);
    if ($fileData === false) return _uploadFailure($conn,$userId,$ip,$originalName,0,null,$context,"Invalid base64 data");
    $fileSize = strlen($fileData);
    if ($fileSize > $config['max_size']) return _uploadFailure($conn,$userId,$ip,$originalName,$fileSize,null,$context,"File exceeds limit");
    $tmpFile = tempnam(sys_get_temp_dir(), 'upload_');
    if (!$tmpFile || !file_put_contents($tmpFile, $fileData)) return _uploadFailure($conn,$userId,$ip,$originalName,$fileSize,null,$context,"Failed to process upload");
    $detectedMime = null;
    if (function_exists('finfo_open')) { $fi = finfo_open(FILEINFO_MIME_TYPE); $detectedMime = finfo_file($fi,$tmpFile); finfo_close($fi);
        if (!_isAllowedMime($ext,$detectedMime)) { @unlink($tmpFile); return _uploadFailure($conn,$userId,$ip,$originalName,$fileSize,$detectedMime,$context,"MIME mismatch"); }
    }
    if (_containsPhpCode($tmpFile)) { @unlink($tmpFile); return _uploadFailure($conn,$userId,$ip,$originalName,$fileSize,$detectedMime,$context,"File contains embedded script code"); }
    $newFilename = _generateSafeFilename($ext);
    $absDir = _getAbsoluteUploadDir($config['upload_dir']);
    if (!_ensureDirectoryExists($absDir)) { @unlink($tmpFile); return _uploadFailure($conn,$userId,$ip,$originalName,$fileSize,$detectedMime,$context,"Failed to create upload directory"); }
    if (!rename($tmpFile, $absDir.$newFilename)) { if (!copy($tmpFile,$absDir.$newFilename)) { @unlink($tmpFile); return _uploadFailure($conn,$userId,$ip,$originalName,$fileSize,$detectedMime,$context,"Failed to save file"); } @unlink($tmpFile); }
    @chmod($absDir.$newFilename, 0644);
    _logAudit($conn,$userId,$ip,$originalName,$newFilename,$fileSize,$detectedMime,$context,'accepted');
    return ['success'=>true,'filename'=>$newFilename,'original_name'=>$originalName,'relative_path'=>$config['upload_dir'].$newFilename,'file_size'=>$fileSize,'mime_type'=>$detectedMime??'application/octet-stream','error'=>null];
}

function getUploadContextConfig($context) { $c = UPLOAD_CONTEXTS; return $c[$context] ?? null; }

function _getContextConfig($ctx, $opt = []) { $c = UPLOAD_CONTEXTS; if (!isset($c[$ctx])) return null; $cfg = $c[$ctx];
    if (!empty($opt['allowed_extensions'])) $cfg['allowed_extensions'] = $opt['allowed_extensions'];
    if (!empty($opt['max_size'])) $cfg['max_size'] = $opt['max_size'];
    if (!empty($opt['upload_dir'])) $cfg['upload_dir'] = $opt['upload_dir']; return $cfg; }

function _sanitizeFilename($n) { $n=str_replace("\0",'',$n); $n=str_replace(['/','\\','..'],'',$n); $n=preg_replace('/[\x00-\x1F\x7F]/','',$n); return trim($n)?:'unnamed_file'; }
function _hasDoubleExtension($f) { $p=explode('.',$f); if(count($p)<=2) return false; $b=BLOCKED_EXTENSIONS; for($i=0;$i<count($p)-1;$i++) if(in_array(strtolower($p[$i]),$b)) return true; return false; }
function _isAllowedMime($ext,$mime) { $m=UPLOAD_MIME_MAP; if(!isset($m[$ext])) return true; return in_array($mime,$m[$ext]); }
function _containsPhpCode($path) { $s=@filesize($path); if($s===false||$s>10*1024*1024) return false; $c=@file_get_contents($path); if($c===false) return false;
    foreach(['/<\?php/i','/<\?=/','/<\?[\s\n\r]/','\/<%[\s\n\r]/','\/eval\s*\(/i','\/base64_decode\s*\(/i','\/system\s*\(/i','\/exec\s*\(/i','\/passthru\s*\(/i','\/shell_exec\s*\(/i','\/proc_open\s*\(/i'] as $p) if(preg_match($p,$c)) { error_log("[File Upload Security] Script code in: ".basename($path)); return true; } return false; }
function _generateSafeFilename($ext) { return uniqid('',true).'_'.time().'.'.$ext; }
function _getAbsoluteUploadDir($rel) { $root=realpath(__DIR__.'/..') ?: dirname(__DIR__); return rtrim($root.DIRECTORY_SEPARATOR.str_replace('/',DIRECTORY_SEPARATOR,$rel),DIRECTORY_SEPARATOR).DIRECTORY_SEPARATOR; }
function _ensureDirectoryExists($d) { if(is_dir($d)) return true; return @mkdir($d,0755,true); }
function _uploadErrorMessage($c) { $m=[UPLOAD_ERR_INI_SIZE=>'File exceeds server limit',UPLOAD_ERR_FORM_SIZE=>'File exceeds form limit',UPLOAD_ERR_PARTIAL=>'Partially uploaded',UPLOAD_ERR_NO_FILE=>'No file uploaded',UPLOAD_ERR_NO_TMP_DIR=>'Missing temp dir',UPLOAD_ERR_CANT_WRITE=>'Write failed',UPLOAD_ERR_EXTENSION=>'Stopped by extension']; return $m[$c]??'Unknown error'; }
function _uploadFailure($conn,$uid,$ip,$orig,$sz,$mime,$ctx,$reason) { _logAudit($conn,$uid,$ip,$orig,null,$sz,$mime,$ctx,'rejected',$reason); error_log("[File Upload Rejected] user={$uid} ip={$ip} file={$orig} ctx={$ctx} reason={$reason}"); return ['success'=>false,'filename'=>null,'original_name'=>$orig,'relative_path'=>null,'file_size'=>$sz,'mime_type'=>$mime,'error'=>$reason]; }
function _logAudit($conn,$uid,$ip,$orig,$saved,$sz,$mime,$ctx,$status,$reason=null) { if(!$conn) return; $sql="INSERT INTO file_upload_audit (user_id,ip_address,original_filename,saved_filename,file_size,mime_type,upload_context,status,rejection_reason) VALUES (?,?,?,?,?,?,?,?,?)";
    $stmt=@mysqli_prepare($conn,$sql); if(!$stmt){$a=$status==='accepted'?'ACCEPTED':'REJECTED'; error_log("[Upload Audit][{$a}] user={$uid} file={$orig} ctx={$ctx}".($reason?" reason={$reason}":'')); return;}
    $saved=$saved??''; $mime=$mime??''; $reason=$reason??''; mysqli_stmt_bind_param($stmt,'isssissss',$uid,$ip,$orig,$saved,$sz,$mime,$ctx,$status,$reason);
    @mysqli_stmt_execute($stmt); mysqli_stmt_close($stmt); }

function ensureUploadDirectorySecurity($dir) { $p=rtrim($dir,'/\\').DIRECTORY_SEPARATOR.'.htaccess'; if(file_exists($p)) return true;
    $c="# Prevent PHP execution\n<IfModule mod_php.c>\nphp_flag engine off\n</IfModule>\n<IfModule mod_php7.c>\nphp_flag engine off\n</IfModule>\n<IfModule mod_php8.c>\nphp_flag engine off\n</IfModule>\n<FilesMatch \"\\.(php|phtml|php3|php4|php5|php7|php8|phar|cgi|pl|py|rb|sh|bat|cmd|exe|com)$\">\nRequire all denied\n</FilesMatch>\n<IfModule mod_headers.c>\nHeader set X-Content-Type-Options \"nosniff\"\n</IfModule>";
    return @file_put_contents($p,$c)!==false; }
?>
FILEUPLOADER;
}
