<?php
/**
 * Leave Sync Configuration Setup
 * 
 * This script helps you configure the leave sync tracking system
 * for your another project. Update the configuration and run the main script.
 */

echo "=== LEAVE SYNC TRACKING CONFIGURATION ===\n\n";

// Configuration form
echo "Please provide the following information:\n\n";

// Database configuration
echo "1. DATABASE CONFIGURATION:\n";
echo "   Database Server (default: localhost): ";
$db_server = trim(fgets(STDIN)) ?: 'localhost';

echo "   Database Username (default: root): ";
$db_username = trim(fgets(STDIN)) ?: 'root';

echo "   Database Password (default: empty): ";
$db_password = trim(fgets(STDIN)) ?: '';

echo "   Database Name: ";
$db_name = trim(fgets(STDIN));
if (empty($db_name)) {
    echo "   Error: Database name is required!\n";
    exit(1);
}

echo "\n2. GOOGLE SHEETS CONFIGURATION:\n";
echo "   Google Sheet ID: ";
$sheet_id = trim(fgets(STDIN));
if (empty($sheet_id)) {
    echo "   Error: Google Sheet ID is required!\n";
    exit(1);
}

echo "   Tab Name (default: Leave_Requests): ";
$tab_name = trim(fgets(STDIN)) ?: 'Leave_Requests';

echo "\n3. FILE PATHS:\n";
echo "   AJAX directory (default: ajax): ";
$ajax_dir = trim(fgets(STDIN)) ?: 'ajax';

echo "   Includes directory (default: includes): ";
$includes_dir = trim(fgets(STDIN)) ?: 'includes';

echo "   Assets JS directory (default: assets/js): ";
$assets_dir = trim(fgets(STDIN)) ?: 'assets/js';

// Create directories if they don't exist
if (!is_dir($ajax_dir)) {
    mkdir($ajax_dir, 0755, true);
    echo "   Created directory: {$ajax_dir}\n";
}

if (!is_dir($includes_dir)) {
    mkdir($includes_dir, 0755, true);
    echo "   Created directory: {$includes_dir}\n";
}

if (!is_dir($assets_dir)) {
    mkdir($assets_dir, 0755, true);
    echo "   Created directory: {$assets_dir}\n";
}

// Generate configuration file
$config_content = "<?php
/**
 * Leave Sync Configuration
 * Generated by setup_leave_sync_config.php
 */

// Database Configuration
define('DB_SERVER', '{$db_server}');
define('DB_USERNAME', '{$db_username}');
define('DB_PASSWORD', '{$db_password}');
define('DB_NAME', '{$db_name}');

// Leave System Configuration
define('LEAVE_SHEET_ID', '{$sheet_id}');
define('LEAVE_TAB_REQUESTS', '{$tab_name}');

// File Paths
define('AJAX_DIR', '{$ajax_dir}');
define('INCLUDES_DIR', '{$includes_dir}');
define('ASSETS_DIR', '{$assets_dir}');
?>";

file_put_contents('leave_sync_config.php', $config_content);
echo "\n✓ Configuration file created: leave_sync_config.php\n";

// Update the main implementation script
$main_script = file_get_contents('implement_leave_sync_tracking.php');

// Replace configuration section
$new_config = "// Configuration - Load from config file
require_once 'leave_sync_config.php';

\$DB_SERVER = DB_SERVER;
\$DB_USERNAME = DB_USERNAME;
\$DB_PASSWORD = DB_PASSWORD;
\$DB_NAME = DB_NAME;
\$LEAVE_SHEET_ID = LEAVE_SHEET_ID;
\$LEAVE_TAB_REQUESTS = LEAVE_TAB_REQUESTS;";

$main_script = preg_replace(
    '/\/\/ Configuration - UPDATE THESE FOR YOUR TARGET DATABASE.*?\$LEAVE_TAB_REQUESTS = \'Leave_Requests\';/s',
    $new_config,
    $main_script
);

// Update file paths in the script
$main_script = str_replace('ajax/get_sync_status.php', $ajax_dir . '/get_sync_status.php', $main_script);
$main_script = str_replace('includes/leave_sync_functions.php', $includes_dir . '/leave_sync_functions.php', $main_script);
$main_script = str_replace('assets/js/leave_sync_status.js', $assets_dir . '/leave_sync_status.js', $main_script);

file_put_contents('implement_leave_sync_tracking.php', $main_script);

echo "\n=== CONFIGURATION COMPLETED ===\n";
echo "Next steps:\n";
echo "1. Review the configuration in leave_sync_config.php\n";
echo "2. Run: php implement_leave_sync_tracking.php\n";
echo "3. Follow the implementation guide\n\n";

echo "Configuration Summary:\n";
echo "- Database: {$db_name}@{$db_server}\n";
echo "- Sheet ID: {$sheet_id}\n";
echo "- Tab Name: {$tab_name}\n";
echo "- AJAX Dir: {$ajax_dir}\n";
echo "- Includes Dir: {$includes_dir}\n";
echo "- Assets Dir: {$assets_dir}\n";
?>
